

const Page = document.createElement('div');
Page.classList.add('mainpage');

    createFirstPage();
    function createFirstPage() {
   
        Page.classList.add('homepage');
        Page.classList.remove('mainpage');
        Page.classList.remove('referencepage');
      
        const Header = document.createElement('div');
        Header.innerHTML = "Find Out Your <br>  Carbon Footprint!";
        Header.classList.add('HeaderM');

        const homeButton = document.createElement('button');
        homeButton.textContent = "Learn More";

        homeButton.addEventListener('click', () => {
         Page.innerHTML = '';
         Page.textContent = '';
            createSecondPage();
        });

        Page.appendChild(Header);
        Page.appendChild(homeButton);
        document.body.appendChild(Page);
    }


    

    function createSecondPage() {
       
        Page.classList.add('secondPageDiv');
        Page.classList.add('mainpage');
        Page.classList.remove('referencepage');
        
        Page.innerHTML = "<h5>Choose Your Mode of Transportation</h5>";
    
        const carImg = document.createElement('img');
        carImg.classList.add('carImg');
        carImg.src ='Car.png';
        Page.appendChild(carImg);
    
        const carButton = document.createElement('button');
        carButton.addEventListener('click', () => {
            document.body.innerHTML = '';
            TripTime('car');
        });
        carButton.textContent = 'Car';
        Page.appendChild(carButton);
        carButton.classList.add('car');
    
        const busImg = document.createElement('img');
        busImg.classList.add('busImg');
        busImg.src = 'bus.png';
        Page.appendChild(busImg);
    
        const busButton = document.createElement('button');
        busButton.addEventListener('click', () => {
            document.body.innerHTML = '';
            TripTime('bus');
        });
        busButton.textContent = 'Bus';
        Page.appendChild(busButton);
        busButton.classList.add('bus');
    
        const trainImg = document.createElement('img');
        trainImg.classList.add('trainImg');
        trainImg.src = 'Train.png';
        Page.appendChild(trainImg);
    
        const trainButton = document.createElement('button');
        trainButton.addEventListener('click', () => {
            document.body.innerHTML = '';
            TripTime('train');
        });
        trainButton.textContent = 'Train';
        Page.appendChild(trainButton);
        trainButton.classList.add('train');
    
  
        document.body.appendChild(Page); 
    }
    



const homeLink = document.getElementById("homeLink");

homeLink.addEventListener("click", function(event) {
     event.preventDefault();
     Page.classList.remove('secondPageDiv');
     Page.classList.remove('awarenessPage');
     Page.classList.remove('referencepage');
     Page.innerHTML = '';
     Page.textContent = '';
     createFirstPage();

   
  
   
});



const awarenessLink = document.getElementById("awarenessLink");

awarenessLink.addEventListener("click", function(event) {
    event.preventDefault();
    
    Page.classList.remove('referencepage');
    Page.classList.remove('secondPageDiv');
    Page.textContent = "";
    Page.innerHTML = "";
    Page.classList.add('mainpage');
  

    Page.innerHTML+=" <h2> General Awareness on Carbon Emission <h2>";
 


    Page.classList.add('awarenessPage');
  
    Page.innerHTML += " <h3> Carbon dioxide emissions from transportation are a significant contributor to climate change. In Saudi Arabia alone, transportation emissions reached a staggering 277.74 million tonnes of CO₂ in 2022. These emissions not only contribute to global warming but also lead to poor air quality and environmental degradation.<br><br>Our Purpose<br><br>Our project aims to shed light on the daily carbon emissions generated by individual transportation choices. By illustrating the immense difference in emissions between various modes of transport, we hope to inspire people to opt for more sustainable alternatives available within the Kingdom.<br><br>Join Us in Making a Difference<br><br>Every journey counts. By making informed decisions about how we travel, we can collectively reduce our carbon footprint and contribute to Saudi Arabia's ambitious goal of achieving zero net emissions by 2060. While many sustainability initiatives focus on large-scale solutions, we believe in the power of individual actions. By providing users with a platform to calculate their carbon emissions per trip, rather than per kilometer, we aim to offer a more personalized and relatable perspective. This approach aligns with Saudi Arabia's Vision 2030, which emphasizes the importance of reducing carbon emissions at both the individual and national levels.<br><br>How You Can Get Involved<br><br>Explore our website to learn more about the environmental impact of different modes of transportation and discover practical tips for reducing your carbon footprint. Share our message with your friends, family, and colleagues to spread awareness and inspire collective action towards a more sustainable future.<br><br>Together, let's drive change and harness the power of public transportation for a greener, healthier Saudi Arabia.<br><br>Join the movement. Drive sustainably. </h3>";
  

    document.body.appendChild(Page);
});




function TripTime(viechle)
{
   const tripTime = document.createElement('div');
   tripTime.classList.add('thirdPage');

   const tripTimeQ = document.createElement('div');
   tripTimeQ.classList.add('thirdPageH');
   tripTimeQ.textContent= "Enter your Trip Distance in Kilometres ";
   tripTime.appendChild(tripTimeQ);

   const editTime = document.createElement('div');
   editTime.classList.add('editableBox');;
   editTime.contentEditable = true;
   editTime.textContent=" ";
   tripTime.appendChild(editTime);

   const calculateButton = document.createElement('button');
   calculateButton.textContent = "Calculate";
   tripTime.appendChild(calculateButton);

    calculateButton.addEventListener('click', function() {

    const editedContent = editTime.textContent;
    const numericContent = editedContent.replace(/\D/g, ''); 
    editTime.textContent = numericContent;



    const editedTime = editTime.textContent;

    if(viechle==='car')
    {

      carCarbonEmission(editedTime, viechle);

    }

    else if (viechle==='bus')
    {
       
          busCarbonEmission(editedTime, viechle);
    }

    else
    {
        trainCarbonEmission(editedTime, viechle);
    }
    

});


document.body.appendChild(tripTime);



}


 class CarbonEmission
 {
    constructor(time, viechle)
    {
        this.time=time;
        this.viechle=viechle;
    }
    
    carCarbon() {
            const carCarbonE = this.time * 133; 
            return carCarbonE;
        }
    

    busCarbon() 
        {
            const carCarbonE = this.time * 20; 
            return carCarbonE;
        }
    

    trainCarbon() 
        {
            const carCarbonE = this.time * 10; 
            return carCarbonE;
        }
    
}


    


function carCarbonEmission(editedTime, viechle)
{
    document.body.textContent='';
    const emission = new CarbonEmission(editedTime, viechle);
    const carCarbonC = emission.carCarbon(); 


    const carbonEDivH = document.createElement('div');
    const carbonEDiv = document.createElement('div');
    
    const fourthPage = document.createElement('div');
    carbonEDivH.classList.add('HeaderV')
   

    carbonEDivH.textContent+= "With the car ";
    carbonEDiv.textContent+= carCarbonC; 
    carbonEDiv.textContent+= " grams of Co2 are emitted";
    
    fourthPage.appendChild(carbonEDivH);
    fourthPage.appendChild(carbonEDiv);
  

    const Tree = document.createElement('div');
    Tree.classList.add('TreeQ');
    Tree.textContent+= "How many trees need to be planted per year to offset your  net carbon emissions?";
    fourthPage.appendChild(Tree);

    // const TreeButton = document.createElement('button');
    // TreeButton.classList.add('Treebtn');
    // TreeButton.textContent += "See Trees";
    // fourthPage.appendChild(TreeButton);

    TreesPerEmission(carCarbonC,viechle,fourthPage);
     
    
     const OthersButton = document.createElement('button');
     OthersButton.classList.add('Treebtn');
     OthersButton.textContent += "Compare Emissions";
     fourthPage.appendChild(OthersButton);
   
   OthersButton.addEventListener('click', () =>
   {
    const carbonODiv = document.createElement('div');
    
    const carbonHDiv = document.createElement('div');
    carbonHDiv.textContent+="For the same trip";

    carbonODiv.textContent+= "A bus emits ";
    const carCarbonB = emission.busCarbon(); 
    carbonODiv.textContent+= carCarbonB; 
    carbonODiv.textContent+= " grams of Co2"; 
    

    const carbonTDiv = document.createElement('div');
    carbonTDiv.textContent ="A train emits ";
    const carCarbonT = emission.trainCarbon(); 
    carbonTDiv.textContent+= carCarbonT;
    carbonTDiv.textContent+= " grams of Co2";

    fourthPage.classList.add('fourthPage');
    fourthPage.appendChild(carbonHDiv);
    fourthPage.appendChild(carbonODiv);
    fourthPage.appendChild(carbonTDiv);


    carbonEDiv.classList.add('carbon');
    carbonODiv.classList.add('carbon');
    carbonHDiv.classList.add('HeaderV');
    carbonTDiv.classList.add('carbon');

   });
    
    document.body.appendChild(fourthPage);
  
    // TreeButton.addEventListener('click', () => {
       
    // TreesPerEmission(carCarbonC,viechle,fourthPage);

    // });
   

}

function busCarbonEmission(editedTime, viechle)
{
    document.body.textContent='';
    const emission = new CarbonEmission(editedTime, viechle);
    const busCarbonE = emission.busCarbon(); 
    
    
    const fourthPage = document.createElement('div');

    const carbonEDiv = document.createElement('div');
    
    const carbonEDivH = document.createElement('div');
    carbonEDivH.classList.add('HeaderV')
    fourthPage.appendChild(carbonEDivH)

    carbonEDivH.textContent+= "With the Bus";
    carbonEDiv.textContent+= busCarbonE; 
    carbonEDiv.textContent+= " grams of Co2 are emitted";
    

    fourthPage.appendChild(carbonEDiv);

    TreesPerEmission(busCarbonE,viechle,fourthPage);

    const OthersButton = document.createElement('button');
    OthersButton.classList.add('Treebtn');
    OthersButton.textContent += "Compare Emissions";
    fourthPage.appendChild(OthersButton);
    
    OthersButton.addEventListener('click', () =>
    {
    const carbonODiv = document.createElement('div');

    const carbonHDiv = document.createElement('div');
    carbonHDiv.textContent+="For the same trip:";

    carbonODiv.textContent+= "A car emits ";
    const carCarbonC = emission.carCarbon(); 
    carbonODiv.textContent+= carCarbonC; 
    carbonODiv.textContent+= " grams of Co2"; 
   
    
    const carbonTDiv = document.createElement('div');
    carbonTDiv.textContent ="A train emits ";
    const carCarbonT = emission.trainCarbon(); 
    carbonTDiv.textContent+= carCarbonT;
    carbonTDiv.textContent+= " grams of Co2";

    fourthPage.classList.add('fourthPage');
    fourthPage.appendChild(carbonHDiv);
    fourthPage.appendChild(carbonODiv);
    fourthPage.appendChild(carbonTDiv);


    carbonEDiv.classList.add('carbon');
    carbonODiv.classList.add('carbon');
    carbonHDiv.classList.add('HeaderV');
    carbonTDiv.classList.add('carbon');

    });
      
    document.body.appendChild(fourthPage);



}

function trainCarbonEmission(editedTime, viechle)
{
    document.body.textContent='';
    const emission = new CarbonEmission(editedTime, viechle);
    const trainCarbonE = emission.trainCarbon();


    const carbonEDivH = document.createElement('div');
    const carbonEDiv = document.createElement('div');
    
    const fourthPage = document.createElement('div');
    carbonEDivH.classList.add('HeaderV')
    fourthPage.appendChild(carbonEDivH)

    carbonEDivH.textContent+= "With the train";
    carbonEDiv.textContent+= trainCarbonE; 
    carbonEDiv.textContent+= " grams of Co2 are emitted";
    
  
    fourthPage.appendChild(carbonEDiv);

    TreesPerEmission(busCarbonE,viechle,fourthPage);
    
    const OthersButton = document.createElement('button');
    OthersButton.classList.add('Treebtn');
    OthersButton.textContent += "Compare Emissions";
    fourthPage.appendChild(OthersButton);
    
    OthersButton.addEventListener('click', () =>
    {
   
    const carbonODiv = document.createElement('div');

    
    const carbonHDiv = document.createElement('div');
    carbonHDiv.textContent+="For the same trip";

    carbonODiv.textContent+= "A car emits ";
    const carCarbonC = emission.carCarbon(); 
    carbonODiv.textContent+= carCarbonC; 
    carbonODiv.textContent+= " grams of Co2"; 

    const carbonBDiv = document.createElement('div');
    carbonBDiv.textContent+= "A bus emits ";
    const carCarbonB = emission.busCarbon(); 
    carbonBDiv.textContent+= carCarbonB; 
    carbonBDiv.textContent+= " grams of Co2"; 
   
    fourthPage.classList.add('fourthPage');
    fourthPage.appendChild(carbonHDiv);
    fourthPage.appendChild(carbonODiv);
    fourthPage.appendChild(carbonBDiv);

    carbonEDiv.classList.add('carbon');
    carbonODiv.classList.add('carbon');
    carbonHDiv.classList.add('HeaderV');
    carbonBDiv.classList.add('carbon');

    });
    
    document.body.appendChild(fourthPage);

   

}



function TreesPerEmission(emission, viechle,fourthPage) {
    
    
    fourthPage.textContent='';
    const fifthPage = document.createElement('div');
    fifthPage.classList.add('fifthPage');

    const TreeDiv = document.createElement('div');
    TreeDiv.textContent += "With the " + viechle + " as your mode of transportation, the carbon emissions are equivalent to ";
    const Trees = (12 * (((emission * 30) / 1000) / 21.77)).toFixed(2);
    TreeDiv.textContent += Trees + " trees per year";
    TreeDiv.classList.add('HeaderV');
 
    
    const Treepic = document.createElement('div');
    Treepic.classList.add('TreeBackg');
       
 
    const numTrees = Math.ceil(Trees); 
    for (let i = 0; i < numTrees; i++) {
        const treeImg = document.createElement('img');
        treeImg.src = 'Trees.png'; 
        treeImg.alt = 'Tree';
        treeImg.classList.add('tree');
        Treepic.appendChild(treeImg);
    }

    fifthPage.appendChild(TreeDiv);
    fifthPage.appendChild(Treepic);

    document.body.appendChild(fifthPage);
}


const refLink = document.getElementById("refLink");

refLink.addEventListener("click", function(event) {
   
   
    event.preventDefault();

   



    Page.innerHTML="";
    Page.textContent="";
    Page.innerHTML += "<h2> Assumptions </h2>";
    Page.innerHTML+= "<h3> hi </h3>";
    Page.classList.add('referencepage');
  
});